### ISSUE TITLE
How to change the value of SM_MODULE_DIR?

### ISSUE THREAD

**Issue by mshseek** [aws-samples/amazon-sagemaker-script-mode#2]
In the [tf-eager-script-mode](https://github.com/aws-samples/amazon-sagemaker-script-mode/tree/master/tf-eager-script-mode) example, is there an argument that I can pass to some function to change the value of `SM_MODULE_DIR`?

The default value is `s3://sagemaker-{aws-region}-{aws-id}/{training-job-name}/source/sourcedir.tar.gz` which means it will always create a new bucket. I already have a bucket that I would like to save the compressed source code to. How can I modify `SM_MODULE_DIR` so that the source code will be saved to a specific bucket?

**Comment by rabowskyb** [comment]
Hello, for each training job the code is saved to a folder within the same S3 bucket which is re-used, a new bucket is not created for each training job. This convention is used to enable SageMaker Search (see the SageMaker console) so model versions and the code used to create them can be grouped together and made searchable and trackable.

**Comment by mshseek** [comment]
Currently, the notebook always saves the training job code to the `sagemaker-{aws-region}-{aws-id}` bucket. How can I change which bucket the training job code gets saved to? For example, I already have a bucket named `sagemaker-models` and would like to save both the training job code and model artifacts to this bucket.

**Comment by rabowskyb** [comment]
Some further points:
(1) "SM_MODEL_DIR":  this env var always points to "/opt/ml/model" inside of the container not a S3 location. Model artifacts must be saved to this path for the training job to upload them to S3.
(2) You can override where the model gets saved to by specifying "output_path" of TensorFlow estimator if you are using the sagemaker-python-sdk. If you are using Boto saved model location can be specified with the CreateTrainingJob call. 
(3) As for where the source file is saved. You can just upload the source code to any bucket and use that S3 location as "source_dir" in TensorFlow estimator. This is the document - https://sagemaker.readthedocs.io/en/stable/using_tf.html
(4)  Saving the model to a different bucket shouldn't' affect anything. But you may run into some problems if your bucket name doesn't start with "sagemaker"; it depends on what role you are using to run the training job. The default policy only grants access to buckets with names that start with "sagemaker".

**Comment by mshseek** [comment]
I understand what the `SM_MODEL_DIR ` env var does and how to modify it.

What about  `SM_MODULE_DIR`? In the example given, this is the location where the source file is zipped and uploaded to **after** training is complete.  How can I change this location to another S3 bucket?

**Comment by rabowskyb** [comment]
See point number 3 in my last comment -- this is the only way to control the source code location, there is no direct way to control SM_MODULE_DIR :
(3) As for where the source file is saved. You can just upload the source code to any bucket and use that S3 location as "source_dir" in TensorFlow estimator. This is the document - https://sagemaker.readthedocs.io/en/stable/using_tf.html

**Comment by austinmw** [comment]
Not being able to change `SM_MODULE_DIR` makes things very ugly in S3. For example, I have a bucket named `sagemaker-research` with subdirectories like `datasets`, `classification-jobs`, `object-detection-jobs`, etc. I can specify that a training job's output is placed into, for example, `classification-jobs`, but instead of placing the source code upload directly next to the output, it's placed in the root path of the bucket, really cluttering my s3 organization.

We should be able to change this with either a `module_dir` hyperparameter or by passing a `SM_MODULE_DIR` environment variable to the estimators.

**Comment by rabowskyb** [comment]
Did you try specifying a source_dir?

**Comment by leolorenzoluis** [comment]
@rabowskyb 
> Did you try specifying a source_dir?

I specified source_dir and output_path and it's still uploading the generated model at the root bucket.

**Comment by ksanjeevan** [comment]
Hey @austinmw I was running into the same issue, using `code_location` for PyTorch [Framework](https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.Framework) combined with `output_path` lets me have the model and source outputs in the same s3 location. Hope it helps!

**Comment by drewthayer** [comment]
I have the same problem as the OP and was expecting functionality like @austinmw described: A way to set SM_MODULE_DIR. The problem is, the way sagemaker currently works, I get folders written in my output s3 bucket at different levels.

-  I can set MODEL_DIR with output_path passed to Estimator(), and everything in opt/ml/model will be conveniently zipped and uploaded to MODEL_DIR. That's great.
- specifically, SM_HP_MODEL_DIR = s3://bucket/project/model_name/model/
  - (where model_name = estimator.latest_training_job.name)
- I want the source.tar.gz and tensor board files to save to s3://bucket/project/model_name/source/
- instead, source.tar.gz is being saved to SM_MODULE_DIR, and I we cannot set a subfolder for this path; it seems like it only writes to the root bucket: s3://bucket/model_name/source/

The result is a cluttered bucket:
```
bucket/
-project/
    - model_1/ (with model files from /opt/ml/model/)
    - model_2/
    - model_3/
    - etc...
- model_1/ (with source/)
- model_2/
- model_3/
- etc...
```

I can't save the directories with source/ inside project/. Any chance we could get a --module-dir cmd line arg, or another way to modify the SM_MODULE_DIR environment variable?

**Comment by rabowskyb** [comment]
Hello, could you please file an issue on the GitHub repository for the SageMaker SDK?  The link is https://github.com/aws/sagemaker-python-sdk.  Thanks!

**Comment by mhwilder** [comment]
It looks like some of the issues faced here will be solved by setting the ```code_location``` argument when creating the estimator. This will change where the source files are saved on S3. See general SageMaker Framework docs here: [https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.Framework](https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.Framework)

**Comment by mhwilder** [comment]
> Hey @austinmw I was running into the same issue, using `code_location` for PyTorch [Framework](https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.Framework) combined with `output_path` lets me have the model and source outputs in the same s3 location. Hope it helps!

This solved the issue for me using the TensorFlow estimator. The key is the ```code_location``` argument for the generic Framework class.
