### ISSUE TITLE
What is the correct value for model_dir for TensorFlow estimator in script mode?

### ISSUE THREAD

**Issue by hsm207** [aws-samples/amazon-sagemaker-script-mode#3]
In the [tf-eager-sm-scriptmode.ipynb](https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-eager-script-mode/tf-eager-sm-scriptmode.ipynb) example, `model_dir` is defined as `/opt/ml/model`:

![image](https://user-images.githubusercontent.com/2398765/54865882-90756280-4da7-11e9-9dcb-1ba63f6ff294.png)

But the documentation for TensorFlow says that `model_dir` should be an S3 location:

![image](https://user-images.githubusercontent.com/2398765/54865887-c74b7880-4da7-11e9-8f3e-0810f465ddab.png)

Is the documentation outdated? It looks like `model_dir` in the documentation should be changed to `output_path`.

Also, based on reading other documentation, I get the impression that if my training script generates the usual SavedModel files and other files like evaluation metrics, I must write the SavedModel files to `/opt/ml/model` and evaluation metrics file to `/opt/ml/output`. If I were to write both files to `/opt/ml/model`, then the output will not be serveable. Is this correct, and if yes, how do I get sagemaker to export the the files written in `/opt/ml/output` to an S3 bucket?

**Comment by rabowskyb** [comment]
Hello, any artifacts placed in opt/ml/model are uploaded to S3 automatically by Script Mode containers.  This is true for both local mode training and hosted training.  To demonstrate this, the TF 1.x eager mode notebook uses the aws s3 cp command to fetch the artifacts after training.  Sorry about the confusion in the documentation, please see this link for further details:  https://sagemaker.readthedocs.io/en/stable/using_tf.html.

Having extraneous files in the opt/ml/model directory should be fine, but YMMV -- TensorFlow Serving scans for a correctly formatted SavedModel and loads it if its exists.  The TF 1.x eager mode example in this repo shows this, it is saving an extraneous model checkpoint file along with a SavedModel to that directory and TensorFlow Serving disregards the checkpoint file.  (However, if the directory ONLY contains a checkpoint file and no SavedModel, TensorFlow Serving will crash because it does need a SavedModel, it cannot load a bare checkpoint file.)
