### ISSUE TITLE
Error when processing sklearn_processor.run(...

### ISSUE THREAD

**Issue by AliNGatGeeks** [aws-samples/amazon-sagemaker-script-mode#31]
IN THIS repo:
https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-2-workflow/tf-2-workflow.ipynb

Running sklearn_processor.run(etc... 

leads to following error: 
miniconda3/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

  import imp
INPUT FILE LIST: 
['/opt/ml/processing/input/x_test.npy']
Traceback (most recent call last):
  File "/opt/ml/processing/input/code/preprocessing1.py", line 18, in <module>
    raw_y = np.load(y)
NameError: name 'y' is not defined

**Comment by rabowskyb** [comment]
Hello, thanks for bringing this to our attention.  Unfortunately, since that example is in the **Older Resources** section, we do not actively maintain it anymore.  We strongly suggest you consider as an alternative the following example that uses SageMaker Pipelines instead of Step Functions; it does everything the latter example does, plus much more.  

     https://github.com/aws-samples/amazon-sagemaker-script-mode/tree/master/tf-2-workflow-smpipelines

We've clarified the README to indicate the **Older Resources** are not maintained, apologies for the confusion.
